// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TS.DAL;

namespace TS.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180130000714_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TS.DTO.Classes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<string>("Cpf");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Nome");

                    b.Property<int?>("RelatorioVendaId");

                    b.Property<string>("Rg");

                    b.Property<string>("Telefone");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioVendaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TS.DTO.Classes.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Status");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("TS.DTO.Classes.RelatorioVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("TS.DTO.Classes.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("Data");

                    b.Property<int?>("FormaPagamentoId");

                    b.Property<decimal>("Preco");

                    b.Property<int?>("RelatorioVendaId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("RelatorioVendaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("TS.DTO.Classes.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");
                });

            modelBuilder.Entity("TS.DTO.Classes.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Senha");

                    b.Property<int?>("TipoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TS.DTO.Classes.Cliente", b =>
                {
                    b.HasOne("TS.DTO.Classes.RelatorioVenda")
                        .WithMany("Clientes")
                        .HasForeignKey("RelatorioVendaId");

                    b.HasOne("TS.DTO.Classes.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("TS.DTO.Classes.Cliente", "UsuarioId");
                });

            modelBuilder.Entity("TS.DTO.Classes.Sessao", b =>
                {
                    b.HasOne("TS.DTO.Classes.Cliente", "Cliente")
                        .WithMany("Sessoes")
                        .HasForeignKey("ClienteId");

                    b.HasOne("TS.DTO.Classes.Pagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId");

                    b.HasOne("TS.DTO.Classes.RelatorioVenda")
                        .WithMany("Sessoes")
                        .HasForeignKey("RelatorioVendaId");
                });

            modelBuilder.Entity("TS.DTO.Classes.Usuario", b =>
                {
                    b.HasOne("TS.DTO.Classes.TipoUsuario", "Tipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
